In [1]:
#using sql in pandas
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
#metrics is confusion matrix used to calculate accuracy

In [4]:
quality = pd.read_csv('quality.csv')
quality.dtypes

MemberID                  int64
InpatientDays             int64
ERVisits                  int64
OfficeVisits              int64
Narcotics                 int64
DaysSinceLastERVisit    float64
Pain                      int64
TotalVisits               int64
ProviderCount             int64
MedicalClaims             int64
ClaimLines                int64
StartedOnCombination       bool
AcuteDrugGapSmall         int64
PoorCare                  int64
dtype: object

In [5]:
quality

,MemberID,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,StartedOnCombination,AcuteDrugGapSmall,PoorCare
0,1,0,0,18,1,731.000000,10,18,21,93,222,False,0,0
1,2,1,1,6,1,411.000000,0,8,27,19,115,False,1,0
2,3,0,0,5,3,731.000000,10,5,16,27,148,False,5,0
3,4,0,1,19,0,158.000000,34,20,14,59,242,False,0,0
4,5,8,2,19,3,449.000000,10,29,24,51,204,False,0,0
5,6,2,0,9,2,731.000000,6,11,40,53,156,False,4,1
6,7,16,1,8,1,173.958333,4,25,19,40,261,False,0,0
7,8,2,0,8,0,731.000000,5,10,11,28,87,False,0,0
8,9,2,1,4,3,45.000000,5,7,28,20,98,False,0,1
9,10,4,2,0,2,104.000000,2,6,21,17,66,False,0,0
10,11,6,5,20,2,156.000000,9,31,19,43,126,False,2,0
11,12,0,0,7,4,731.000000,0,7,8,23,41,False,2,0
12,13,0,1,3,1,389.000000,23,4,13,18,70,False,0,0
13,14,1,1,20,3,594.958333,16,22,18,48,133,False,0,0
14,15,6,2,31,3,640.958333,70,39,28,101,233,False,0,0
15,16,0,0,8,0,731.000000,0,8,5,19,48,False,0,0
16,17,2,0,9,0,731.000000,29,11,22,39,120,False,0,0
17,18,3,0,20,1,731.000000,13,23,17,34,73,False,3,1
18,19,0,0,14,0,731.000000,6,14,12,28,90,False,1,0
19,20,0,1,20,0,263.958333,34,21,27,53,153,False,0,0
20,21,5,4,14,1,132.000000,38,23,27,49,148,True,0,1
21,22,0,1,9,1,465.000000,0,10,12,17,91,False,0,0
22,23,3,1,12,0,263.958333,1,16,24,44,164,False,3,0
23,24,8,4,6,2,120.000000,15,18,35,59,232,False,0,1
24,25,0,0,14,1,731.000000,0,14,18,33,82,False,2,0
25,26,0,1,7,0,440.000000,3,8,25,31,96,False,0,0
26,27,3,0,12,0,731.000000,25,15,25,21,65,False,0,0
27,28,0,2,3,2,78.000000,9,5,20,43,117,False,0,1
28,29,0,0,18,32,731.000000,7,18,79,76,158,True,9,1
29,30,13,5,21,6,75.000000,60,39,36,45,248,True,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,102,1,2,11,1,318.000000,3,14,19,22,97,False,0,0
102,103,3,4,14,1,483.000000,1,21,42,34,60,False,6,1
103,104,0,0,16,10,731.000000,5,16,20,50,97,False,5,1
104,105,0,0,15,25,731.000000,1,15,15,21,45,False,16,1
105,106,2,0,28,59,731.000000,10,30,33,47,89,False,71,1
106,107,0,2,25,20,327.000000,19,27,36,46,207,False,3,1
107,108,0,0,5,11,731.000000,5,5,22,53,103,False,0,0
108,109,0,0,12,0,731.000000,0,12,20,39,110,False,0,0
109,110,0,0,7,21,731.000000,0,7,24,18,151,False,8,1
110,111,0,1,24,1,581.958333,20,25,42,40,111,False,3,0
111,112,1,1,29,40,391.000000,45,31,33,60,188,False,8,1
112,113,2,2,22,0,349.000000,47,26,20,43,264,False,0,0
113,114,0,0,14,25,731.000000,2,14,14,31,107,False,13,1
114,115,0,0,12,8,731.000000,13,12,36,50,158,False,1,0
115,116,0,4,10,1,78.000000,65,14,11,38,185,False,0,0
116,117,0,0,21,25,731.000000,1,21,8,34,42,False,12,1
117,118,0,2,16,3,247.958333,49,18,49,41,120,False,0,0
118,119,0,1,22,9,87.000000,0,23,29,44,176,False,1,0
119,120,0,0,9,0,731.000000,2,9,20,59,141,False,3,0
120,121,0,0,9,1,731.000000,3,9,21,41,118,False,2,0
121,122,0,0,8,0,731.000000,11,8,32,37,116,False,0,0
122,123,2,0,7,1,731.000000,2,9,24,18,79,False,0,0
123,124,5,1,17,0,380.000000,20,23,20,32,84,False,1,0
124,125,0,0,23,0,731.000000,0,23,34,58,121,False,3,1
125,126,0,0,6,0,731.000000,0,6,21,25,51,False,5,0
126,127,1,1,5,3,444.000000,0,7,11,11,36,False,0,0
127,128,1,0,3,2,731.000000,0,4,35,18,106,False,2,0
128,129,15,11,5,9,180.958333,95,31,56,43,265,False,3,0
129,130,0,2,14,1,216.958333,5,16,26,41,138,False,1,1
130,131,30,1,22,3,452.000000,38,53,20,103,189,False,13,0

In [7]:
# we can perform sql on data frames using this library
from pandasql import sqldf

In [8]:
#* means all columns
sqldf("select * from quality", locals())#select all columns with all rows

,MemberID,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,StartedOnCombination,AcuteDrugGapSmall,PoorCare
0,1,0,0,18,1,731.000000,10,18,21,93,222,0,0,0
1,2,1,1,6,1,411.000000,0,8,27,19,115,0,1,0
2,3,0,0,5,3,731.000000,10,5,16,27,148,0,5,0
3,4,0,1,19,0,158.000000,34,20,14,59,242,0,0,0
4,5,8,2,19,3,449.000000,10,29,24,51,204,0,0,0
5,6,2,0,9,2,731.000000,6,11,40,53,156,0,4,1
6,7,16,1,8,1,173.958333,4,25,19,40,261,0,0,0
7,8,2,0,8,0,731.000000,5,10,11,28,87,0,0,0
8,9,2,1,4,3,45.000000,5,7,28,20,98,0,0,1
9,10,4,2,0,2,104.000000,2,6,21,17,66,0,0,0
10,11,6,5,20,2,156.000000,9,31,19,43,126,0,2,0
11,12,0,0,7,4,731.000000,0,7,8,23,41,0,2,0
12,13,0,1,3,1,389.000000,23,4,13,18,70,0,0,0
13,14,1,1,20,3,594.958333,16,22,18,48,133,0,0,0
14,15,6,2,31,3,640.958333,70,39,28,101,233,0,0,0
15,16,0,0,8,0,731.000000,0,8,5,19,48,0,0,0
16,17,2,0,9,0,731.000000,29,11,22,39,120,0,0,0
17,18,3,0,20,1,731.000000,13,23,17,34,73,0,3,1
18,19,0,0,14,0,731.000000,6,14,12,28,90,0,1,0
19,20,0,1,20,0,263.958333,34,21,27,53,153,0,0,0
20,21,5,4,14,1,132.000000,38,23,27,49,148,1,0,1
21,22,0,1,9,1,465.000000,0,10,12,17,91,0,0,0
22,23,3,1,12,0,263.958333,1,16,24,44,164,0,3,0
23,24,8,4,6,2,120.000000,15,18,35,59,232,0,0,1
24,25,0,0,14,1,731.000000,0,14,18,33,82,0,2,0
25,26,0,1,7,0,440.000000,3,8,25,31,96,0,0,0
26,27,3,0,12,0,731.000000,25,15,25,21,65,0,0,0
27,28,0,2,3,2,78.000000,9,5,20,43,117,0,0,1
28,29,0,0,18,32,731.000000,7,18,79,76,158,1,9,1
29,30,13,5,21,6,75.000000,60,39,36,45,248,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,102,1,2,11,1,318.000000,3,14,19,22,97,0,0,0
102,103,3,4,14,1,483.000000,1,21,42,34,60,0,6,1
103,104,0,0,16,10,731.000000,5,16,20,50,97,0,5,1
104,105,0,0,15,25,731.000000,1,15,15,21,45,0,16,1
105,106,2,0,28,59,731.000000,10,30,33,47,89,0,71,1
106,107,0,2,25,20,327.000000,19,27,36,46,207,0,3,1
107,108,0,0,5,11,731.000000,5,5,22,53,103,0,0,0
108,109,0,0,12,0,731.000000,0,12,20,39,110,0,0,0
109,110,0,0,7,21,731.000000,0,7,24,18,151,0,8,1
110,111,0,1,24,1,581.958333,20,25,42,40,111,0,3,0
111,112,1,1,29,40,391.000000,45,31,33,60,188,0,8,1
112,113,2,2,22,0,349.000000,47,26,20,43,264,0,0,0
113,114,0,0,14,25,731.000000,2,14,14,31,107,0,13,1
114,115,0,0,12,8,731.000000,13,12,36,50,158,0,1,0
115,116,0,4,10,1,78.000000,65,14,11,38,185,0,0,0
116,117,0,0,21,25,731.000000,1,21,8,34,42,0,12,1
117,118,0,2,16,3,247.958333,49,18,49,41,120,0,0,0
118,119,0,1,22,9,87.000000,0,23,29,44,176,0,1,0
119,120,0,0,9,0,731.000000,2,9,20,59,141,0,3,0
120,121,0,0,9,1,731.000000,3,9,21,41,118,0,2,0
121,122,0,0,8,0,731.000000,11,8,32,37,116,0,0,0
122,123,2,0,7,1,731.000000,2,9,24,18,79,0,0,0
123,124,5,1,17,0,380.000000,20,23,20,32,84,0,1,0
124,125,0,0,23,0,731.000000,0,23,34,58,121,0,3,1
125,126,0,0,6,0,731.000000,0,6,21,25,51,0,5,0
126,127,1,1,5,3,444.000000,0,7,11,11,36,0,0,0
127,128,1,0,3,2,731.000000,0,4,35,18,106,0,2,0
128,129,15,11,5,9,180.958333,95,31,56,43,265,0,3,0
129,130,0,2,14,1,216.958333,5,16,26,41,138,0,1,1
130,131,30,1,22,3,452.000000,38,53,20,103,189,0,13,0

In [12]:
sqldf("select MemberID,InpatientDays from quality", locals())

     MemberID  InpatientDays
0           1              0
1           2              1
2           3              0
3           4              0
4           5              8
5           6              2
6           7             16
7           8              2
8           9              2
9          10              4
10         11              6
11         12              0
12         13              0
13         14              1
14         15              6
15         16              0
16         17              2
17         18              3
18         19              0
19         20              0
20         21              5
21         22              0
22         23              3
23         24              8
24         25              0
25         26              0
26         27              3
27         28              0
28         29              0
29         30             13
..        ...            ...
101       102              1
102       103              3
103       104              0
104       105              0
105       106              2
106       107              0
107       108              0
108       109              0
109       110              0
110       111              0
111       112              1
112       113              2
113       114              0
114       115              0
115       116              0
116       117              0
117       118              0
118       119              0
119       120              0
120       121              0
121       122              0
122       123              2
123       124              5
124       125              0
125       126              0
126       127              1
127       128              1
128       129             15
129       130              0
130       131             30

[131 rows x 2 columns]

In [13]:
sqldf("select * from quality where poorcare=1", locals())#to print only the rows where value of poorcare = 1

,MemberID,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,StartedOnCombination,AcuteDrugGapSmall,PoorCare
0,6,2,0,9,2,731.000000,6,11,40,53,156,0,4,1
1,9,2,1,4,3,45.000000,5,7,28,20,98,0,0,1
2,18,3,0,20,1,731.000000,13,23,17,34,73,0,3,1
3,21,5,4,14,1,132.000000,38,23,27,49,148,1,0,1
4,24,8,4,6,2,120.000000,15,18,35,59,232,0,0,1
5,28,0,2,3,2,78.000000,9,5,20,43,117,0,0,1
6,29,0,0,18,32,731.000000,7,18,79,76,158,1,9,1
7,30,13,5,21,6,75.000000,60,39,36,45,248,1,1,1
8,35,0,8,46,2,35.000000,41,54,55,94,295,0,2,1
9,41,1,0,15,0,731.000000,2,16,11,38,86,1,0,1
10,46,0,0,21,25,731.000000,1,21,8,34,42,0,12,1
11,47,30,8,31,3,42.000000,53,69,43,99,342,0,0,1
12,48,0,1,5,2,323.000000,0,6,8,12,20,0,8,1
13,56,12,7,46,0,19.000000,27,65,18,78,243,1,0,1
14,60,12,6,17,2,16.000000,25,35,47,128,410,0,2,1
15,62,0,1,13,30,321.000000,31,14,34,62,343,0,6,1
16,64,9,0,13,0,731.000000,36,22,36,37,147,0,0,1
17,83,0,0,22,9,731.000000,92,22,10,41,151,0,6,1
18,84,1,7,26,46,87.000000,53,34,82,165,559,0,17,1
19,85,8,2,9,0,258.958333,0,19,17,19,103,0,7,1
20,99,1,1,15,2,242.958333,0,17,12,25,53,0,1,1
21,101,0,0,26,0,731.000000,17,26,14,50,116,0,0,1
22,103,3,4,14,1,483.000000,1,21,42,34,60,0,6,1
23,104,0,0,16,10,731.000000,5,16,20,50,97,0,5,1
24,105,0,0,15,25,731.000000,1,15,15,21,45,0,16,1
25,106,2,0,28,59,731.000000,10,30,33,47,89,0,71,1
26,107,0,2,25,20,327.000000,19,27,36,46,207,0,3,1
27,110,0,0,7,21,731.000000,0,7,24,18,151,0,8,1
28,112,1,1,29,40,391.000000,45,31,33,60,188,0,8,1
29,114,0,0,14,25,731.000000,2,14,14,31,107,0,13,1
30,117,0,0,21,25,731.000000,1,21,8,34,42,0,12,1
31,125,0,0,23,0,731.000000,0,23,34,58,121,0,3,1
32,130,0,2,14,1,216.958333,5,16,26,41,138,0,1,1

In [14]:
sqldf("select MemberID from quality where poorcare=1", locals())#to print specific column and specific rows

    MemberID
0          6
1          9
2         18
3         21
4         24
5         28
6         29
7         30
8         35
9         41
10        46
11        47
12        48
13        56
14        60
15        62
16        64
17        83
18        84
19        85
20        99
21       101
22       103
23       104
24       105
25       106
26       107
27       110
28       112
29       114
30       117
31       125
32       130

In [18]:
sqldf("select * from quality where MemberID>100 AND poorcare=1",locals())

,MemberID,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,StartedOnCombination,AcuteDrugGapSmall,PoorCare
0,101,0,0,26,0,731.000000,17,26,14,50,116,0,0,1
1,103,3,4,14,1,483.000000,1,21,42,34,60,0,6,1
2,104,0,0,16,10,731.000000,5,16,20,50,97,0,5,1
3,105,0,0,15,25,731.000000,1,15,15,21,45,0,16,1
4,106,2,0,28,59,731.000000,10,30,33,47,89,0,71,1
5,107,0,2,25,20,327.000000,19,27,36,46,207,0,3,1
6,110,0,0,7,21,731.000000,0,7,24,18,151,0,8,1
7,112,1,1,29,40,391.000000,45,31,33,60,188,0,8,1
8,114,0,0,14,25,731.000000,2,14,14,31,107,0,13,1
9,117,0,0,21,25,731.000000,1,21,8,34,42,0,12,1
10,125,0,0,23,0,731.000000,0,23,34,58,121,0,3,1
11,130,0,2,14,1,216.958333,5,16,26,41,138,0,1,1

In [19]:
sqldf("select * from quality where MemberID>100 OR poorcare=1",locals())

,MemberID,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,StartedOnCombination,AcuteDrugGapSmall,PoorCare
0,6,2,0,9,2,731.000000,6,11,40,53,156,0,4,1
1,9,2,1,4,3,45.000000,5,7,28,20,98,0,0,1
2,18,3,0,20,1,731.000000,13,23,17,34,73,0,3,1
3,21,5,4,14,1,132.000000,38,23,27,49,148,1,0,1
4,24,8,4,6,2,120.000000,15,18,35,59,232,0,0,1
5,28,0,2,3,2,78.000000,9,5,20,43,117,0,0,1
6,29,0,0,18,32,731.000000,7,18,79,76,158,1,9,1
7,30,13,5,21,6,75.000000,60,39,36,45,248,1,1,1
8,35,0,8,46,2,35.000000,41,54,55,94,295,0,2,1
9,41,1,0,15,0,731.000000,2,16,11,38,86,1,0,1
10,46,0,0,21,25,731.000000,1,21,8,34,42,0,12,1
11,47,30,8,31,3,42.000000,53,69,43,99,342,0,0,1
12,48,0,1,5,2,323.000000,0,6,8,12,20,0,8,1
13,56,12,7,46,0,19.000000,27,65,18,78,243,1,0,1
14,60,12,6,17,2,16.000000,25,35,47,128,410,0,2,1
15,62,0,1,13,30,321.000000,31,14,34,62,343,0,6,1
16,64,9,0,13,0,731.000000,36,22,36,37,147,0,0,1
17,83,0,0,22,9,731.000000,92,22,10,41,151,0,6,1
18,84,1,7,26,46,87.000000,53,34,82,165,559,0,17,1
19,85,8,2,9,0,258.958333,0,19,17,19,103,0,7,1
20,99,1,1,15,2,242.958333,0,17,12,25,53,0,1,1
21,101,0,0,26,0,731.000000,17,26,14,50,116,0,0,1
22,102,1,2,11,1,318.000000,3,14,19,22,97,0,0,0
23,103,3,4,14,1,483.000000,1,21,42,34,60,0,6,1
24,104,0,0,16,10,731.000000,5,16,20,50,97,0,5,1
25,105,0,0,15,25,731.000000,1,15,15,21,45,0,16,1
26,106,2,0,28,59,731.000000,10,30,33,47,89,0,71,1
27,107,0,2,25,20,327.000000,19,27,36,46,207,0,3,1
28,108,0,0,5,11,731.000000,5,5,22,53,103,0,0,0
29,109,0,0,12,0,731.000000,0,12,20,39,110,0,0,0
30,110,0,0,7,21,731.000000,0,7,24,18,151,0,8,1
31,111,0,1,24,1,581.958333,20,25,42,40,111,0,3,0
32,112,1,1,29,40,391.000000,45,31,33,60,188,0,8,1
33,113,2,2,22,0,349.000000,47,26,20,43,264,0,0,0
34,114,0,0,14,25,731.000000,2,14,14,31,107,0,13,1
35,115,0,0,12,8,731.000000,13,12,36,50,158,0,1,0
36,116,0,4,10,1,78.000000,65,14,11,38,185,0,0,0
37,117,0,0,21,25,731.000000,1,21,8,34,42,0,12,1
38,118,0,2,16,3,247.958333,49,18,49,41,120,0,0,0
39,119,0,1,22,9,87.000000,0,23,29,44,176,0,1,0
40,120,0,0,9,0,731.000000,2,9,20,59,141,0,3,0
41,121,0,0,9,1,731.000000,3,9,21,41,118,0,2,0
42,122,0,0,8,0,731.000000,11,8,32,37,116,0,0,0
43,123,2,0,7,1,731.000000,2,9,24,18,79,0,0,0
44,124,5,1,17,0,380.000000,20,23,20,32,84,0,1,0
45,125,0,0,23,0,731.000000,0,23,34,58,121,0,3,1
46,126,0,0,6,0,731.000000,0,6,21,25,51,0,5,0
47,127,1,1,5,3,444.000000,0,7,11,11,36,0,0,0
48,128,1,0,3,2,731.000000,0,4,35,18,106,0,2,0
49,129,15,11,5,9,180.958333,95,31,56,43,265,0,3,0
50,130,0,2,14,1,216.958333,5,16,26,41,138,0,1,1
51,131,30,1,22,3,452.000000,38,53,20,103,189,0,13,0

In [22]:
sqldf("select * from quality limit 5", locals())

,MemberID,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,StartedOnCombination,AcuteDrugGapSmall,PoorCare
0,1,0,0,18,1,731.0,10,18,21,93,222,0,0,0
1,2,1,1,6,1,411.0,0,8,27,19,115,0,1,0
2,3,0,0,5,3,731.0,10,5,16,27,148,0,5,0
3,4,0,1,19,0,158.0,34,20,14,59,242,0,0,0
4,5,8,2,19,3,449.0,10,29,24,51,204,0,0,0

In [27]:
sqldf("select * from quality where poorcare=1",locals())
sqldf("select count(*) from quality where poorcare=1",locals())

   count(*)
0        33

In [29]:
sqldf("select count(MemberID) from quality where poorcare=1", locals())

   count(MemberID)
0               33

In [31]:
sqldf("select max(MemberID) from quality", locals())

   max(MemberID)
0            131

In [32]:
#max,min,avg,mean

In [33]:
#like keyword
#sqldf("select * from quality where name like'%a'",names())

In [2]:
#to separate test data from train data, we use sklearnmodelsselection

In [5]:
qualityTrain, qualityTest = train_test_split(quality, test_size = 0.3,random_state = 88) #here 0.3 implies 30 percent

In [7]:
qualityTest.dtypes

MemberID                  int64
InpatientDays             int64
ERVisits                  int64
OfficeVisits              int64
Narcotics                 int64
DaysSinceLastERVisit    float64
Pain                      int64
TotalVisits               int64
ProviderCount             int64
MedicalClaims             int64
ClaimLines                int64
StartedOnCombination       bool
AcuteDrugGapSmall         int64
PoorCare                  int64
dtype: object

In [8]:
qualityTrain

,MemberID,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,StartedOnCombination,AcuteDrugGapSmall,PoorCare
60,61,0,0,7,0,731.000000,0,7,10,19,49,False,0,0
111,112,1,1,29,40,391.000000,45,31,33,60,188,False,8,1
123,124,5,1,17,0,380.000000,20,23,20,32,84,False,1,0
43,44,4,4,19,1,43.000000,104,27,56,38,219,False,1,0
57,58,0,0,25,34,731.000000,23,25,24,84,186,False,0,0
125,126,0,0,6,0,731.000000,0,6,21,25,51,False,5,0
26,27,3,0,12,0,731.000000,25,15,25,21,65,False,0,0
9,10,4,2,0,2,104.000000,2,6,21,17,66,False,0,0
83,84,1,7,26,46,87.000000,53,34,82,165,559,False,17,1
18,19,0,0,14,0,731.000000,6,14,12,28,90,False,1,0
103,104,0,0,16,10,731.000000,5,16,20,50,97,False,5,1
92,93,0,2,15,0,547.958333,11,17,13,30,65,False,0,0
30,31,5,2,2,0,30.000000,0,9,24,19,108,False,0,0
55,56,12,7,46,0,19.000000,27,65,18,78,243,True,0,1
19,20,0,1,20,0,263.958333,34,21,27,53,153,False,0,0
121,122,0,0,8,0,731.000000,11,8,32,37,116,False,0,0
93,94,1,0,15,0,731.000000,0,16,25,45,126,False,4,0
58,59,0,0,19,19,731.000000,3,19,28,36,149,False,8,0
6,7,16,1,8,1,173.958333,4,25,19,40,261,False,0,0
81,82,4,5,13,2,6.000000,26,22,10,25,152,False,1,0
22,23,3,1,12,0,263.958333,1,16,24,44,164,False,3,0
35,36,0,3,37,2,430.000000,26,40,34,63,159,False,2,0
117,118,0,2,16,3,247.958333,49,18,49,41,120,False,0,0
113,114,0,0,14,25,731.000000,2,14,14,31,107,False,13,1
68,69,0,0,6,0,731.000000,3,6,31,27,89,True,0,0
27,28,0,2,3,2,78.000000,9,5,20,43,117,False,0,1
72,73,0,0,1,1,731.000000,1,1,8,33,134,False,0,0
56,57,8,0,10,0,731.000000,0,18,21,29,85,False,3,0
49,50,2,0,6,3,731.000000,0,8,16,22,41,False,10,0
65,66,0,0,25,0,731.000000,1,25,12,47,93,False,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,103,3,4,14,1,483.000000,1,21,42,34,60,False,6,1
78,79,0,0,8,0,731.000000,13,8,15,17,66,False,0,0
40,41,1,0,15,0,731.000000,2,16,11,38,86,True,0,1
1,2,1,1,6,1,411.000000,0,8,27,19,115,False,1,0
77,78,9,4,6,2,346.000000,10,19,21,31,185,False,1,0
99,100,3,1,7,0,648.958333,8,11,13,20,124,False,3,0
13,14,1,1,20,3,594.958333,16,22,18,48,133,False,0,0
29,30,13,5,21,6,75.000000,60,39,36,45,248,True,1,1
86,87,1,0,7,4,731.000000,10,8,15,37,148,False,2,0
10,11,6,5,20,2,156.000000,9,31,19,43,126,False,2,0
70,71,0,5,14,0,59.000000,52,19,52,58,186,False,0,0
39,40,0,0,8,0,731.000000,3,8,44,27,79,False,6,0
7,8,2,0,8,0,731.000000,5,10,11,28,87,False,0,0
89,90,0,1,0,0,175.958333,0,1,7,19,35,False,0,0
90,91,11,8,9,11,160.000000,43,28,32,38,207,False,2,0
71,72,5,0,18,1,731.000000,13,23,30,42,115,False,7,0
4,5,8,2,19,3,449.000000,10,29,24,51,204,False,0,0
75,76,5,0,7,3,731.000000,10,12,17,33,67,False,0,0
126,127,1,1,5,3,444.000000,0,7,11,11,36,False,0,0
34,35,0,8,46,2,35.000000,41,54,55,94,295,False,2,1
48,49,0,1,2,0,718.000000,0,3,19,26,232,False,0,0
122,123,2,0,7,1,731.000000,2,9,24,18,79,False,0,0
108,109,0,0,12,0,731.000000,0,12,20,39,110,False,0,0
69,70,0,1,13,6,156.000000,18,14,33,31,124,False,0,0
112,113,2,2,22,0,349.000000,47,26,20,43,264,False,0,0
97,98,0,7,11,1,68.000000,31,18,16,24,146,False,1,0
62,63,10,6,20,1,151.000000,9,36,45,118,308,False,4,0
101,102,1,2,11,1,318.000000,3,14,19,22,97,False,0,0
106,107,0,2,25,20,327.000000,19,27,36,46,207,False,3,1
32,33,0,0,6,0,731.000000,17,6,14,35,83,False,1,0

In [11]:
np.shape(qualityTrain)

(91, 14)

In [15]:
qualityTest.shape
#np.shape(qualityTest)

(40, 14)

In [18]:
pd.DataFrame(qualityTrain["PoorCare"].value_counts()).T

           0   1
PoorCare  71  20

In [19]:
pd.DataFrame(qualityTest["PoorCare"].value_counts()).T

           0   1
PoorCare  27  13

In [21]:
import statsmodels.api as sm
#to find logIt we've imported this module

In [27]:
QualityLog = sm.Logit.from_formula('PoorCare~OfficeVisits+Narcotics', data=quality).fit()

Optimization terminated successfully.
         Current function value: 0.444464
         Iterations 6

In [28]:
QualityLog.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:               PoorCare   No. Observations:                  131
Model:                          Logit   Df Residuals:                      128
Method:                           MLE   Df Model:                            2
Date:                Wed, 18 Jul 2018   Pseudo R-squ.:                  0.2125
Time:                        00:34:50   Log-Likelihood:                -58.225
converged:                       True   LL-Null:                       -73.939
                                        LLR p-value:                 1.497e-07
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       -2.5402      0.450     -5.644      0.000      -3.422      -1.658
OfficeVisits     0.0627      0.024      2.615      0.009       0.016       0.110
Narcotics        0.1099      0.033      3.368      0.001       0.046       0.174
================================================================================
"""

In [29]:
QualityLog.fittedvalues

0     -1.301091
1     -2.053908
2     -1.896850
3     -1.348253
4     -1.018564
5     -1.755807
6     -1.928438
7     -2.038334
8     -1.959584
9     -2.320420
10    -1.065725
11    -1.661484
12    -2.242112
13    -0.955829
14    -0.265747
15    -2.038334
16    -1.975600
17    -1.175622
18    -1.661926
19    -1.285518
20    -1.552030
21    -1.865703
22    -1.787396
23    -1.944011
24    -1.552030
25    -2.101069
26    -1.787396
27    -2.132215
28     2.105692
29    -0.563406
         ...
101   -1.740234
102   -1.552030
103   -0.437494
104    1.148214
105    5.700237
106    1.226080
107   -1.017680
108   -1.787396
109    0.206752
110   -0.924683
111    3.674944
112   -1.160048
113    1.085480
114   -0.908226
115   -1.802969
116    1.524623
117   -1.206768
118   -0.170982
119   -1.975600
120   -1.865703
121   -2.038334
122   -1.991173
123   -1.473722
124   -1.097314
125   -2.163804
126   -1.896850
127   -2.132215
128   -1.237472
129   -1.552030
130   -0.830360
Length: 131, dtype: float64

In [33]:
#Predicting the data
predictTrain = QualityLog.predict()

In [34]:
predictTrain

array([ 0.21398145,  0.11365814,  0.13046543,  0.2061562 ,  0.26530723,
        0.14731624,  0.12692356,  0.11523645,  0.12351202,  0.08944589,
        0.25621684,  0.15956287,  0.09603207,  0.27771404,  0.43395139,
        0.11523645,  0.1217887 ,  0.23584035,  0.15950361,  0.21661243,
        0.17479329,  0.13403966,  0.14339234,  0.12520784,  0.17479329,
        0.10899296,  0.14339234,  0.10600486,  0.89145518,  0.36275979,
        0.08205539,  0.57024475,  0.10304834,  0.13409097,  0.63769575,
        0.50019115,  0.1217887 ,  0.12013284,  0.18402754,  0.11523645,
        0.16809466,  0.1217887 ,  0.07308681,  0.22472222,  0.1512718 ,
        0.82121816,  0.43395139,  0.11849645,  0.08205539,  0.13774878,
        0.16809466,  0.31353587,  0.19607838,  0.10899296,  0.10899296,
        0.58554642,  0.12865934,  0.94073415,  0.67694681,  0.22202066,
        0.10899296,  0.82810071,  0.23584035,  0.1512718 ,  0.22472222,
        0.27451304,  0.09072238,  0.14731624,  0.10304834,  0.25630108,
        0.15950361,  0.21398145,  0.08567845,  0.17479329,  0.12520784,
        0.14537075,  0.10600486,  0.12520784,  0.11523645,  0.09739251,
        0.10304834,  0.18170055,  0.45735823,  0.9844208 ,  0.1217887 ,
        0.09201526,  0.15956287,  0.19370419,  0.13046543,  0.07308681,
        0.31718449,  0.13403966,  0.16809466,  0.16809466,  0.11523645,
        0.13046543,  0.27460107,  0.14928322,  0.20110555,  0.10899296,
        0.28718207,  0.14928322,  0.17479329,  0.39233816,  0.75918459,
        0.99666598,  0.77313178,  0.26547956,  0.14339234,  0.55150459,
        0.2840047 ,  0.97527594,  0.23865848,  0.74752954,  0.28736305,
        0.14149007,  0.82121816,  0.23027342,  0.45735823,  0.1217887 ,
        0.13403966,  0.11523645,  0.12013284,  0.18637755,  0.25024356,
        0.10304834,  0.13046543,  0.10600486,  0.22487626,  0.17479329,
        0.303569  ])

In [36]:
#do same for 3 variables and for all variab
lrg_2 = sm.Logit.from_formula('PoorCare~OfficeVisits+Narcotics+ProviderCount', data=quality).fit()

Optimization terminated successfully.
         Current function value: 0.443563
         Iterations 6

In [37]:
lrg_2.fittedvalues

0     -1.345767
1     -1.992458
2     -1.934589
3     -1.460898
4     -1.041573
5     -1.587874
6     -1.949329
7     -2.132206
8     -1.882264
9     -2.289941
10    -1.138233
11    -1.782472
12    -2.297291
13    -1.038481
14    -0.302521
15    -2.187622
16    -1.972100
17    -1.265693
18    -1.771916
19    -1.282320
20    -1.524386
21    -1.955473
22    -1.778100
23    -1.809581
24    -1.607511
25    -2.061409
26    -1.768864
27    -2.123650
28     2.568552
29    -0.486758
         ...
101   -1.773802
102   -1.385844
103   -0.491130
104    1.038999
105    5.671455
106    1.273108
107   -1.007269
108   -1.815045
109    0.218100
110   -0.800754
111    3.659194
112   -1.229954
113    0.971254
114   -0.795364
115   -1.906200
116    1.325401
117   -0.986198
118   -0.165938
119   -1.990572
120   -1.872348
121   -1.938247
122   -1.961657
123   -1.522500
124   -1.042140
125   -2.156863
126   -1.980769
127   -1.985108
128   -0.911217
129   -1.533622
130   -0.902991
Length: 131, dtype: float64